version: "3"
services:

  database:
    image: sql
    container_name: sql
    ports:
      - "1433:1433"
    networks:
      - test

  backend:
    image: backend
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - test
    depends_on:
      - database

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - test
    depends_on:
      - backend

  test:
    image: test
    networks:
      - test
    depends_on:
      - frontend
      - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    networks:
      - test
    ports: 
      - "4444:4444"

networks:
  test: