USE master;
GO
CREATE DATABASE TCC
/*ON (NAME = tcc_dat, FILENAME = 'C:\db\tccdat.mdf')
LOG ON (NAME = tcc_log, FILENAME = 'C:\db\tcclog.ldf');
GO
USE TCC*/;
GO

CREATE TABLE Curso(
    Id BIGINT NOT NULL PRIMARY KEY IDENTITY,
    Nome VARCHAR(255) NOT NULL
);

CREATE TABLE Turma(
    Id BIGINT NOT NULL PRIMARY KEY IDENTITY,
    IdCurso BIGINT NOT NULL REFERENCES Curso(Id),
    Nome VARCHAR(255) NOT NULL,
    Vagas INT NOT NULL
);

CREATE TABLE Aluno(
    Id BIGINT NOT NULL PRIMARY KEY IDENTITY,
    IdCurso BIGINT NOT NULL REFERENCES Curso(Id),
    Nome VARCHAR(255) NOT NULL
);

CREATE TABLE AlunoTurma(
    IdAluno BIGINT NOT NULL REFERENCES Aluno(Id),
    IdTurma BIGINT NOT NULL REFERENCES Turma(Id),
    CONSTRAINT Pk_AlunoTurma PRIMARY KEY CLUSTERED(IdAluno, IdTurma)
);